version: '3.8'
services:
  vprodb:
    build:
      context: ./Docker-file/db
    container_name: vprodb
    image: dockingsumit/vprodbimage
    ports:
      - "3306:3306"
    volumes:
      - vprodbdata:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=vprodbpass

  vprocache01:
    image: memcached
    ports:
      - "11211:11211"

  vpromq01:
    image: rabbitmq
    ports:
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest

  vproapp:
    build:
      context: ./Docker-file/app
    container_name: vproapp
    image: dockingsumit/vproappimage
    ports:
      - "8080:8080"
    volumes: 
      - vproappdata:/usr/local/tomcat/webapps

  vproweb:
    build:
      context: ./Docker-file/web
    container_name: vproweb
    image: dockingsumit/vprowebimage
    ports:
      - "80:80"
volumes:
  vprodbdata: {}
  vproappdata: {}
